<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_0EPhsAl0Ee6loP0AHmYpgQ" name="procedimento" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_0E0wgAl0Ee6loP0AHmYpgQ" name="Gestao de projetos">
      <elements xmi:type="process:Lane" xmi:id="_0E5pAAl0Ee6loP0AHmYpgQ" name="Gestor de projeto" actor="_WQtDoAl4Ee6loP0AHmYpgQ">
        <elements xmi:type="process:StartEvent" xmi:id="_0FBk0Al0Ee6loP0AHmYpgQ" name="Início de projeto" outgoing="_0NwqEAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0FBk0gl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FBk0Ql0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0FBk0wl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0FEoIAl0Ee6loP0AHmYpgQ" name="Passagem" outgoing="_0NzGUAl0Ee6loP0AHmYpgQ" incoming="_0NwqEAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0FEoIgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FEoIQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0FEoIwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0FEoJgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0FEoJwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0FEoKAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0FEoKgl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0FEoKQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0FEoJAl0Ee6loP0AHmYpgQ" name="Passagem" content="Passagem" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0FEoJQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_0FISgAl0Ee6loP0AHmYpgQ" name="Enviar ao Cliente do documento de requisitos" outgoing="_0N3-0Al0Ee6loP0AHmYpgQ" incoming="_0N2JoAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0FISggl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FISgQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0FISgwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0FIShAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0FIShQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0FIShgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0FISiAl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0FIShwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_0FLV0Al0Ee6loP0AHmYpgQ" name="Solicitar a revisão e validação dos requisitos" outgoing="_0N6bEAl0Ee6loP0AHmYpgQ" incoming="_0N3-0Al0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0FLV0gl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FLV0Ql0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0FLV0wl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0FLV1Al0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0FLV1Ql0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0FLV1gl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0FLV2Al0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0FLV1wl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_0FNyEAl0Ee6loP0AHmYpgQ" name="Cliente aprovou plano de testes?" outgoing="_0N-sgAl0Ee6loP0AHmYpgQ _0OBIwAl0Ee6loP0AHmYpgQ" incoming="_3FImwAnrEe6-OJ1qbTi2_g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0FNyEgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FNyEQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0FNyEwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_0FQOUAl0Ee6loP0AHmYpgQ" name="É necessário levantar requisitos novamente?" outgoing="_0OC98Al0Ee6loP0AHmYpgQ _0OEzIAl0Ee6loP0AHmYpgQ" incoming="_cTfakAl6Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0FQOUgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FQOUQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0FQOUwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0FSqkAl0Ee6loP0AHmYpgQ" name="Testes" outgoing="_3FImwAnrEe6-OJ1qbTi2_g" incoming="_0OEzIAl0Ee6loP0AHmYpgQ _0OGoUAl0Ee6loP0AHmYpgQ _0OIdgAl0Ee6loP0AHmYpgQ _0OKSsAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0FSqkgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FSqkQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0FSqkwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0FSqlgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0FSqlwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0FSqmAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0FSqmgl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0FSqmQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0FSqlAl0Ee6loP0AHmYpgQ" name="Reuniao de trabalho" content="Reuniao de trabalho" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0FSqlQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0FVG0Al0Ee6loP0AHmYpgQ" name="Projeto em produtivo" outgoing="_0ON9EAl0Ee6loP0AHmYpgQ" incoming="_0OMH4Al0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0FVG0gl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FVG0Ql0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0FVG0wl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0FVG1gl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0FVG1wl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0FVG2Al0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0FVG2gl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0FVG2Ql0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0FVG1Al0Ee6loP0AHmYpgQ" name="Projeto em produtivo" content="Projeto em produtivo" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0FVG1Ql0Ee6loP0AHmYpgQ" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0FXjEAl0Ee6loP0AHmYpgQ" name="Fecho do projeto (Encerramento)" outgoing="_0OaxYAl0Ee6loP0AHmYpgQ" incoming="_0OPLMAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0FXjEgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FXjEQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0FXjEwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0FXjFgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0FXjFwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0FXjGAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0FXjGgl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0FXjGQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0FXjFAl0Ee6loP0AHmYpgQ" name="Fecho de projeto" content="Fecho de projeto" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0FXjFQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_0FZ_UAl0Ee6loP0AHmYpgQ" name="Fim de projeto" incoming="_0OgQ8Al0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0FZ_Ugl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FZ_UQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0FZ_Uwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_0FcbkAl0Ee6loP0AHmYpgQ" name="Reportar resultados  da avaliação da satisfação" outgoing="_0OgQ8Al0Ee6loP0AHmYpgQ" incoming="_0OiGIAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0Fcbkgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FcbkQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0Fcbkwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0FcblAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0FcblQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0Fcblgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0FcbmAl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0Fcblwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_0Fe30Al0Ee6loP0AHmYpgQ" name="Tipo de projeto?" outgoing="_0OIdgAl0Ee6loP0AHmYpgQ _0OmXkAl0Ee6loP0AHmYpgQ _0OoMwAl0Ee6loP0AHmYpgQ" incoming="_0Oj7UAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0Fe30gl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0Fe30Ql0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0Fe30wl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0FvWgAl0Ee6loP0AHmYpgQ" name="Parametrização/R&amp;D" outgoing="_0OseMAl0Ee6loP0AHmYpgQ" incoming="_0OqpAAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0FvWggl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FvWgQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0FvWgwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0FvWhgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0FvWhwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0FvWiAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0FvWigl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0FvWiQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0FvWhAl0Ee6loP0AHmYpgQ" name="Parametrização" content="Parametrização" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0FvWhQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_0FyZ0Al0Ee6loP0AHmYpgQ" name="Formação necessária?" outgoing="_0OvhgAl0Ee6loP0AHmYpgQ _0Ox9wAl0Ee6loP0AHmYpgQ" incoming="_0N6bEAl0Ee6loP0AHmYpgQ _N10FgAl5Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0FyZ0gl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0FyZ0Ql0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0FyZ0wl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0F02EAl0Ee6loP0AHmYpgQ" name="Formação" outgoing="_0O0aAAl0Ee6loP0AHmYpgQ" incoming="_0Ox9wAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0F02Egl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0F02EQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0F02Ewl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0F02Fgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0F02Fwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0F02GAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0F02Ggl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0F02GQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0F02FAl0Ee6loP0AHmYpgQ" name="Process_778d11a6-e0f6-4fb6-b183-c2a9220ccdff" content="Process_778d11a6-e0f6-4fb6-b183-c2a9220ccdff" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0F02FQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_0F3SUAl0Ee6loP0AHmYpgQ" name="Gateway_0xkimz4" outgoing="_0OqpAAl0Ee6loP0AHmYpgQ" incoming="_0OvhgAl0Ee6loP0AHmYpgQ _0O1oIAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0F3SUgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0F3SUQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0F3SUwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_0F5ukAl0Ee6loP0AHmYpgQ" name="Projeto do tipo Upgrade ou Consultoria?" outgoing="_0N2JoAl0Ee6loP0AHmYpgQ _0O5SgAl0Ee6loP0AHmYpgQ" incoming="_0O3dUAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0F5ukgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0F5ukQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0F5ukwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0F8x4Al0Ee6loP0AHmYpgQ" name="Levantamento/revisão de requisitos" outgoing="_0O9j8Al0Ee6loP0AHmYpgQ" incoming="_0O7uwAl0Ee6loP0AHmYpgQ _0OC98Al0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0F8x4gl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0F8x4Ql0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0F8x4wl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0F8x5gl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0F8x5wl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0F8x6Al0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0F8x6gl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0F8x6Ql0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0F8x5Al0Ee6loP0AHmYpgQ" name="Levantamento" content="Levantamento" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0F8x5Ql0Ee6loP0AHmYpgQ" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0F_OIAl0Ee6loP0AHmYpgQ" name="Arranque" outgoing="_0O3dUAl0Ee6loP0AHmYpgQ" incoming="_0O-yEAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0F_OIgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0F_OIQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0F_OIwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0F_OJgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0F_OJwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0F_OKAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0F_OKgl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0F_OKQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0F_OJAl0Ee6loP0AHmYpgQ" name="Arranque" content="Arranque" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0F_OJQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_0GBqYAl0Ee6loP0AHmYpgQ" name="Enviar email de estado de progresso" outgoing="_0PDDgAl0Ee6loP0AHmYpgQ" incoming="_0PAnQAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GCRcQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GCRcAl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GCRcgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0GCRcwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0GCRdAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0GCRdQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0GCRdwl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0GCRdgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_0GEGoAl0Ee6loP0AHmYpgQ" name="Gateway_0tseq94" outgoing="_0OKSsAl0Ee6loP0AHmYpgQ" incoming="_0PDDgAl0Ee6loP0AHmYpgQ _0PFfwAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GEGogl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GEGoQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GEGowl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_0GHJ8Al0Ee6loP0AHmYpgQ" name="Enviar email?" outgoing="_0PAnQAl0Ee6loP0AHmYpgQ _0PGt4Al0Ee6loP0AHmYpgQ" incoming="_CsPJAAl5Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GHJ8gl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GHJ8Ql0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GHJ8wl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0GJmMAl0Ee6loP0AHmYpgQ" name="Reunião de steering n3" outgoing="_0Oj7UAl0Ee6loP0AHmYpgQ" incoming="_0OseMAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GJmMgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GJmMQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GJmMwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0GJmNgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0GJmNwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0GJmOAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0GJmOgl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0GJmOQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0GLbYAl0Ee6loP0AHmYpgQ" name="Reuniao de steering" content="Reuniao de steering"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0GLbYQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0GMCcAl0Ee6loP0AHmYpgQ" name="Reunião de steering n2" outgoing="_0O1oIAl0Ee6loP0AHmYpgQ" incoming="_0O0aAAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GMCcgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GMCcQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GMCcwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0GMCdgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0GMpgAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0GMpgQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0GMpgwl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0GMpggl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0GN3oAl0Ee6loP0AHmYpgQ" name="Reuniao de steering" content="Reuniao de steering"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0GN3oQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0GOesAl0Ee6loP0AHmYpgQ" name="Reunião de steering n1" outgoing="_0OuTYAl0Ee6loP0AHmYpgQ" incoming="_0O9j8Al0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GOesgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GOesQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GOeswl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0GOetgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0GOetwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0GOeuAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0GOeugl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0GOeuQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0GQT4Al0Ee6loP0AHmYpgQ" name="Reuniao de steering" content="Reuniao de steering"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0GQT4Ql0Ee6loP0AHmYpgQ" name="1.0" content="1.0"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0GQ68Al0Ee6loP0AHmYpgQ" name="Reunião de trabalho n2" outgoing="_0O7uwAl0Ee6loP0AHmYpgQ" incoming="_0O5SgAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GQ68gl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GQ68Ql0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GQ68wl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0GQ69gl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0GQ69wl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0GQ6-Al0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0GQ6-gl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0GQ6-Ql0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0GTXMAl0Ee6loP0AHmYpgQ" name="Reuniao de trabalho" content="Reuniao de trabalho"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0GTXMQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0GT-QAl0Ee6loP0AHmYpgQ" name="Reunião de trabalho n1" outgoing="_0O-yEAl0Ee6loP0AHmYpgQ" incoming="_0NzGUAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GT-Qgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GT-QQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GT-Qwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0GT-Rgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0GT-Rwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0GT-SAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0GT-Sgl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0GT-SQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0GVzcAl0Ee6loP0AHmYpgQ" name="Reuniao de trabalho" content="Reuniao de trabalho"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0GVzcQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0GWagAl0Ee6loP0AHmYpgQ" name="Reunião de steering n4" outgoing="_0PJKIAl0Ee6loP0AHmYpgQ" incoming="_0OBIwAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GWaggl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GWagQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GWagwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0GWahgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0GWahwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0GWaiAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0GWaigl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0GWaiQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0GYPsAl0Ee6loP0AHmYpgQ" name="Reuniao de steering" content="Reuniao de steering"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0GYPsQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0GY2wAl0Ee6loP0AHmYpgQ" name="Reunião de steering n6" outgoing="_0PKYQAl0Ee6loP0AHmYpgQ" incoming="_0OaxYAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GY2wgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GY2wQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GY2wwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0GY2xgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0GY2xwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0GY2yAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0GY2ygl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0GY2yQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0Gar8Al0Ee6loP0AHmYpgQ" name="Reuniao de steering" content="Reuniao de steering"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0Gar8Ql0Ee6loP0AHmYpgQ" name="1.0" content="1.0"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0GbTAAl0Ee6loP0AHmYpgQ" name="Reunião de steering n5" outgoing="_0OPLMAl0Ee6loP0AHmYpgQ" incoming="_0ON9EAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GbTAgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GbTAQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GbTAwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0GbTBgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0GbTBwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0GbTCAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0GbTCgl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0GbTCQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0GeWUAl0Ee6loP0AHmYpgQ" name="Reuniao de steering" content="Reuniao de steering"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0GeWUQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0GeWUgl0Ee6loP0AHmYpgQ" name="Reunião de trabalho" outgoing="_0OMH4Al0Ee6loP0AHmYpgQ" incoming="_0PJKIAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GeWVAl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GeWUwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GeWVQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0Ge9Ygl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0Ge9Ywl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0Ge9ZAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0Ge9Zgl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0Ge9ZQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0GgykAl0Ee6loP0AHmYpgQ" name="Reuniao de trabalho" content="Reuniao de trabalho"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0GgykQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0GhZoAl0Ee6loP0AHmYpgQ" name="Distribuição da ata da reunião" outgoing="_0OiGIAl0Ee6loP0AHmYpgQ" incoming="_0PKYQAl0Ee6loP0AHmYpgQ">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_0PP30Al0Ee6loP0AHmYpgQ" source="_0PM0gAl0Ee6loP0AHmYpgQ"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GhZogl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GhZoQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GhZowl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0GhZpgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0GhZpwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0GhZqAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0GhZqgl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0GhZqQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0Gj14Al0Ee6loP0AHmYpgQ" name="Distribuicao da ata da reuniao" content="Distribuicao da ata da reuniao"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0Gj14Ql0Ee6loP0AHmYpgQ" name="1.0" content="1.0"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0Gkc8Al0Ee6loP0AHmYpgQ" name="Reunião de progresso n2" outgoing="_0OGoUAl0Ee6loP0AHmYpgQ" incoming="_0OmXkAl0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0Gkc8gl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0Gkc8Ql0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0Gkc8wl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0Gkc9gl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0Gkc9wl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0Gkc-Al0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0Gkc-gl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0Gkc-Ql0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0GmSIAl0Ee6loP0AHmYpgQ" name="Reuniao de progresso" content="Reuniao de progresso"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0GmSIQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_0GngQAl0Ee6loP0AHmYpgQ" name="Reunião de progresso n1" outgoing="_0PFfwAl0Ee6loP0AHmYpgQ" incoming="_0PGt4Al0Ee6loP0AHmYpgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0GngQgl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0GngQQl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0GngQwl0Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0GngRgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0GngRwl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0GngSAl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0GngSgl0Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0GngSQl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_0Gp8gAl0Ee6loP0AHmYpgQ" name="Reuniao de progresso" content="Reuniao de progresso"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_0Gp8gQl0Ee6loP0AHmYpgQ" name="1.0" content="1.0"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_0PM0gAl0Ee6loP0AHmYpgQ" text="Ata correspondente a reunião de fecho de projeto"/>
        <elements xmi:type="process:Task" xmi:id="_gzi60Al5Ee6loP0AHmYpgQ" name="Confirmar necessidade de formaçao" outgoing="_N10FgAl5Ee6loP0AHmYpgQ" incoming="_0OuTYAl0Ee6loP0AHmYpgQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_N1yQUQl5Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_N1yQUAl5Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_N1yQUgl5Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_nRFmAAl5Ee6loP0AHmYpgQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_nRFmAQl5Ee6loP0AHmYpgQ" name="necessitaFormaçao" content="necessitaFormaçao" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_nqmSMAl5Ee6loP0AHmYpgQ" name="necessitaFormaçao" dataType="_0EQIwgl0Ee6loP0AHmYpgQ"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_nRFmAgl5Ee6loP0AHmYpgQ" name="newScript()" content="necessitaFormaçao2" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qeQsoAl5Ee6loP0AHmYpgQ" name="necessitaFormaçao2" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_qeQsoQl5Ee6loP0AHmYpgQ"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_nRFmAwl5Ee6loP0AHmYpgQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_N1yQUwl5Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_N1yQVAl5Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_N1yQVQl5Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_N1yQVwl5Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_N1yQVgl5Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_gzi62gl5Ee6loP0AHmYpgQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_rW3IkAl5Ee6loP0AHmYpgQ" name="confirmarFormacao" content="1a588210-7508-49a4-9280-fcab3b6ff940" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_gzi62Ql5Ee6loP0AHmYpgQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_j3M5EAl5Ee6loP0AHmYpgQ" name="necessitaFormaçao2" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_j3M5EQl5Ee6loP0AHmYpgQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_gzjh4Ql5Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_iKCzsAl5Ee6loP0AHmYpgQ" name="Confirmar necessidade de enviar email" outgoing="_CsPJAAl5Ee6loP0AHmYpgQ" incoming="_0OoMwAl0Ee6loP0AHmYpgQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_CsJpcQl5Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CsJpcAl5Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_CsJpcgl5Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_BJrUoAl6Ee6loP0AHmYpgQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_BJrUoQl6Ee6loP0AHmYpgQ" name="necessitaEnvioEmail" content="necessitaEnvioEmail" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_BhxEgAl6Ee6loP0AHmYpgQ" name="necessitaEnvioEmail" dataType="_0EQIwgl0Ee6loP0AHmYpgQ"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_BJrUogl6Ee6loP0AHmYpgQ" name="newScript()" content="necessitaEnvioEmail2" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_CG05YAl6Ee6loP0AHmYpgQ" name="necessitaEnvioEmail2" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_CG05YQl6Ee6loP0AHmYpgQ"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_BJrUowl6Ee6loP0AHmYpgQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_CsJpcwl5Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_CsJpdAl5Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_CsJpdQl5Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_CsJpdwl5Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_CsJpdgl5Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_iKDayQl5Ee6loP0AHmYpgQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_CskqwAl6Ee6loP0AHmYpgQ" name="necessitaEnvioEmail" content="a4e09345-8512-45a0-a416-7d62877a70ca" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_iKDayAl5Ee6loP0AHmYpgQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_-7JnkAl5Ee6loP0AHmYpgQ" name="necessitaEnvioEmail2" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_-7JnkQl5Ee6loP0AHmYpgQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_iKDaywl5Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_rTq1MAl6Ee6loP0AHmYpgQ" name="Confirmar levantamento de requisitos" outgoing="_cTfakAl6Ee6loP0AHmYpgQ" incoming="_0N-sgAl0Ee6loP0AHmYpgQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_cTc-Ugl6Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_cTc-UQl6Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_cTc-Uwl6Ee6loP0AHmYpgQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_uyu9EAl6Ee6loP0AHmYpgQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_uyu9EQl6Ee6loP0AHmYpgQ" name="necessitaNovosRequisitos" content="necessitaNovosRequisitos" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_vPd8YAl6Ee6loP0AHmYpgQ" name="necessitaNovosRequisitos" dataType="_0EQIwgl0Ee6loP0AHmYpgQ"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_uyu9Egl6Ee6loP0AHmYpgQ" name="newScript()" content="necessitaNovosRequisitos2" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_wF1jsAl6Ee6loP0AHmYpgQ" name="necessitaNovosRequisitos2" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_wF1jsQl6Ee6loP0AHmYpgQ"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_uyu9Ewl6Ee6loP0AHmYpgQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_cTc-VAl6Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_cTc-VQl6Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_cTc-Vgl6Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_cTc-WAl6Ee6loP0AHmYpgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_cTc-Vwl6Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_rTrcSQl6Ee6loP0AHmYpgQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_wjAn4Al6Ee6loP0AHmYpgQ" name="novosRequisitos" content="306e020e-7a82-4625-a1fa-05ee8eda4b5e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_rTrcSAl6Ee6loP0AHmYpgQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_sHVt0Al6Ee6loP0AHmYpgQ" name="necessitaNovosRequisitos2" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_sHVt0Ql6Ee6loP0AHmYpgQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_rTrcSwl6Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_bbzsAAl3Ee6loP0AHmYpgQ" name="projeto" dataType="_0EQIygl0Ee6loP0AHmYpgQ" className="com.company.model.Projecto">
        <defaultValue xmi:type="expression:Expression" xmi:id="_bbzsAQl3Ee6loP0AHmYpgQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_d3ag4Al5Ee6loP0AHmYpgQ" name="necessitaFormaçao" dataType="_0EQIwgl0Ee6loP0AHmYpgQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d3ag4Ql5Ee6loP0AHmYpgQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_90EDsAl5Ee6loP0AHmYpgQ" name="necessitaEnvioEmail" dataType="_0EQIwgl0Ee6loP0AHmYpgQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_90EDsQl5Ee6loP0AHmYpgQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_qntuIAl6Ee6loP0AHmYpgQ" name="necessitaNovosRequisitos" dataType="_0EQIwgl0Ee6loP0AHmYpgQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_qntuIQl6Ee6loP0AHmYpgQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_OXEtkAl7Ee6loP0AHmYpgQ" name="planoTestes" dataType="_0EQIwgl0Ee6loP0AHmYpgQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_OXEtkQl7Ee6loP0AHmYpgQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_0E0wkAl0Ee6loP0AHmYpgQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_ne2mIAmCEe6loP0AHmYpgQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_0E0wkgl0Ee6loP0AHmYpgQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_0E0wkwl0Ee6loP0AHmYpgQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0NwqEAl0Ee6loP0AHmYpgQ" target="_0FEoIAl0Ee6loP0AHmYpgQ" source="_0FBk0Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0NwqEQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0NwqEgl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0NzGUAl0Ee6loP0AHmYpgQ" target="_0GT-QAl0Ee6loP0AHmYpgQ" source="_0FEoIAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0NzGUQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0NzGUgl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0N2JoAl0Ee6loP0AHmYpgQ" name="Não" target="_0FISgAl0Ee6loP0AHmYpgQ" source="_0F5ukAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0N2JoQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0N2Jogl0Ee6loP0AHmYpgQ" name="newScript()" content="projeto.tipo!=&quot;Upgrade&quot;   &amp;&amp;  projeto.tipo!=&quot;Consultoria&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hVxJAAl3Ee6loP0AHmYpgQ" name="projeto" dataType="_0EQIygl0Ee6loP0AHmYpgQ" className="com.company.model.Projecto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0N3-0Al0Ee6loP0AHmYpgQ" target="_0FLV0Al0Ee6loP0AHmYpgQ" source="_0FISgAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0N3-0Ql0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0N3-0gl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0N6bEAl0Ee6loP0AHmYpgQ" target="_0FyZ0Al0Ee6loP0AHmYpgQ" source="_0FLV0Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0N6bEQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0N6bEgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0N-sgAl0Ee6loP0AHmYpgQ" name="Não" target="_rTq1MAl6Ee6loP0AHmYpgQ" source="_0FNyEAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0N-sgQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0N-sggl0Ee6loP0AHmYpgQ" name="newScript()" content="projeto.aprovacaoPlanoTestes==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_5AVvMAnrEe6-OJ1qbTi2_g" name="projeto" dataType="_0EQIygl0Ee6loP0AHmYpgQ" className="com.company.model.Projecto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OBIwAl0Ee6loP0AHmYpgQ" name="Sim" target="_0GWagAl0Ee6loP0AHmYpgQ" source="_0FNyEAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OBIwQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OBIwgl0Ee6loP0AHmYpgQ" name="newScript()" content="projeto.aprovacaoPlanoTestes==true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6P1BIAnrEe6-OJ1qbTi2_g" name="projeto" dataType="_0EQIygl0Ee6loP0AHmYpgQ" className="com.company.model.Projecto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OC98Al0Ee6loP0AHmYpgQ" name="Sim" target="_0F8x4Al0Ee6loP0AHmYpgQ" source="_0FQOUAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OC98Ql0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OC98gl0Ee6loP0AHmYpgQ" name="newScript()" content="necessitaNovosRequisitos.value=true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_-NroIAl6Ee6loP0AHmYpgQ" name="necessitaNovosRequisitos" dataType="_0EQIwgl0Ee6loP0AHmYpgQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OEzIAl0Ee6loP0AHmYpgQ" name="Não" target="_0FSqkAl0Ee6loP0AHmYpgQ" source="_0FQOUAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OEzIQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OEzIgl0Ee6loP0AHmYpgQ" name="newScript()" content="necessitaNovosRequisitos.value=false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="__T2mAAl6Ee6loP0AHmYpgQ" name="necessitaNovosRequisitos" dataType="_0EQIwgl0Ee6loP0AHmYpgQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OGoUAl0Ee6loP0AHmYpgQ" target="_0FSqkAl0Ee6loP0AHmYpgQ" source="_0Gkc8Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OGoUQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OGoUgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OIdgAl0Ee6loP0AHmYpgQ" name="Tipo C" target="_0FSqkAl0Ee6loP0AHmYpgQ" source="_0Fe30Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OIdgQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OIdggl0Ee6loP0AHmYpgQ" name="newScript()" content="projeto.tipo==&quot;C&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AY83wAl5Ee6loP0AHmYpgQ" name="projeto" dataType="_0EQIygl0Ee6loP0AHmYpgQ" className="com.company.model.Projecto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OKSsAl0Ee6loP0AHmYpgQ" target="_0FSqkAl0Ee6loP0AHmYpgQ" source="_0GEGoAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OKSsQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OKSsgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OMH4Al0Ee6loP0AHmYpgQ" target="_0FVG0Al0Ee6loP0AHmYpgQ" source="_0GeWUgl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OMH4Ql0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OMH4gl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0ON9EAl0Ee6loP0AHmYpgQ" target="_0GbTAAl0Ee6loP0AHmYpgQ" source="_0FVG0Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0ON9EQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0ON9Egl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OPLMAl0Ee6loP0AHmYpgQ" target="_0FXjEAl0Ee6loP0AHmYpgQ" source="_0GbTAAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OPLMQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OPLMgl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OaxYAl0Ee6loP0AHmYpgQ" target="_0GY2wAl0Ee6loP0AHmYpgQ" source="_0FXjEAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OaxYQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OaxYgl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OgQ8Al0Ee6loP0AHmYpgQ" target="_0FZ_UAl0Ee6loP0AHmYpgQ" source="_0FcbkAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OgQ8Ql0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OgQ8gl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OiGIAl0Ee6loP0AHmYpgQ" target="_0FcbkAl0Ee6loP0AHmYpgQ" source="_0GhZoAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OiGIQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OiGIgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0Oj7UAl0Ee6loP0AHmYpgQ" target="_0Fe30Al0Ee6loP0AHmYpgQ" source="_0GJmMAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0Oj7UQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0Oj7Ugl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OmXkAl0Ee6loP0AHmYpgQ" name="Tipo A" target="_0Gkc8Al0Ee6loP0AHmYpgQ" source="_0Fe30Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OmXkQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OmXkgl0Ee6loP0AHmYpgQ" name="newScript()" content="projeto.tipo==&quot;A&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="__iNdAAl4Ee6loP0AHmYpgQ" name="projeto" dataType="_0EQIygl0Ee6loP0AHmYpgQ" className="com.company.model.Projecto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OoMwAl0Ee6loP0AHmYpgQ" name="Tipo B" target="_iKCzsAl5Ee6loP0AHmYpgQ" source="_0Fe30Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0Ooz0Al0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0Ooz0Ql0Ee6loP0AHmYpgQ" name="newScript()" content="projeto.tipo==&quot;B&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_-1jyYAl4Ee6loP0AHmYpgQ" name="projeto" dataType="_0EQIygl0Ee6loP0AHmYpgQ" className="com.company.model.Projecto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OqpAAl0Ee6loP0AHmYpgQ" target="_0FvWgAl0Ee6loP0AHmYpgQ" source="_0F3SUAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OqpAQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OqpAgl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OseMAl0Ee6loP0AHmYpgQ" target="_0GJmMAl0Ee6loP0AHmYpgQ" source="_0FvWgAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OseMQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OseMgl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OuTYAl0Ee6loP0AHmYpgQ" target="_gzi60Al5Ee6loP0AHmYpgQ" source="_0GOesAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OuTYQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OuTYgl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0OvhgAl0Ee6loP0AHmYpgQ" name="Não" target="_0F3SUAl0Ee6loP0AHmYpgQ" source="_0FyZ0Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0OwIkAl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0OwIkQl0Ee6loP0AHmYpgQ" name="newScript()" content="necessitaFormaçao.value==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_5RsEsAl5Ee6loP0AHmYpgQ" name="necessitaFormaçao" dataType="_0EQIwgl0Ee6loP0AHmYpgQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0Ox9wAl0Ee6loP0AHmYpgQ" name="Sim" target="_0F02EAl0Ee6loP0AHmYpgQ" source="_0FyZ0Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0Oyk0Al0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0Oyk0Ql0Ee6loP0AHmYpgQ" name="newScript()" content="necessitaFormaçao.value==true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_3f6lEAl5Ee6loP0AHmYpgQ" name="necessitaFormaçao" dataType="_0EQIwgl0Ee6loP0AHmYpgQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0O0aAAl0Ee6loP0AHmYpgQ" target="_0GMCcAl0Ee6loP0AHmYpgQ" source="_0F02EAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0O0aAQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0O0aAgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0O1oIAl0Ee6loP0AHmYpgQ" target="_0F3SUAl0Ee6loP0AHmYpgQ" source="_0GMCcAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0O1oIQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0O1oIgl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0O3dUAl0Ee6loP0AHmYpgQ" target="_0F5ukAl0Ee6loP0AHmYpgQ" source="_0F_OIAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0O3dUQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0O3dUgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0O5SgAl0Ee6loP0AHmYpgQ" name="Sim" target="_0GQ68Al0Ee6loP0AHmYpgQ" source="_0F5ukAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0O5SgQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0O5Sggl0Ee6loP0AHmYpgQ" name="newScript()" content="projeto.tipo==&quot;Upgrade&quot;  || projeto.tipo==&quot;Consultoria&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_fQ68YAl3Ee6loP0AHmYpgQ" name="projeto" dataType="_0EQIygl0Ee6loP0AHmYpgQ" className="com.company.model.Projecto"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0O7uwAl0Ee6loP0AHmYpgQ" target="_0F8x4Al0Ee6loP0AHmYpgQ" source="_0GQ68Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0O7uwQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0O7uwgl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0O9j8Al0Ee6loP0AHmYpgQ" target="_0GOesAl0Ee6loP0AHmYpgQ" source="_0F8x4Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0O9j8Ql0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0O9j8gl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0O-yEAl0Ee6loP0AHmYpgQ" target="_0F_OIAl0Ee6loP0AHmYpgQ" source="_0GT-QAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0O-yEQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0O-yEgl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0PAnQAl0Ee6loP0AHmYpgQ" name="Sim" target="_0GBqYAl0Ee6loP0AHmYpgQ" source="_0GHJ8Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0PAnQQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0PAnQgl0Ee6loP0AHmYpgQ" name="newScript()" content="necessitaEnvioEmail.value==true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_OPi-sAl6Ee6loP0AHmYpgQ" name="necessitaEnvioEmail" dataType="_0EQIwgl0Ee6loP0AHmYpgQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0PDDgAl0Ee6loP0AHmYpgQ" target="_0GEGoAl0Ee6loP0AHmYpgQ" source="_0GBqYAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0PDDgQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0PDDggl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0PFfwAl0Ee6loP0AHmYpgQ" target="_0GEGoAl0Ee6loP0AHmYpgQ" source="_0GngQAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0PFfwQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0PFfwgl0Ee6loP0AHmYpgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0PGt4Al0Ee6loP0AHmYpgQ" name="Não" target="_0GngQAl0Ee6loP0AHmYpgQ" source="_0GHJ8Al0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0PGt4Ql0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0PGt4gl0Ee6loP0AHmYpgQ" name="newScript()" content="necessitaEnvioEmail.value==false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_PWQIEAl6Ee6loP0AHmYpgQ" name="necessitaEnvioEmail" dataType="_0EQIwgl0Ee6loP0AHmYpgQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0PJKIAl0Ee6loP0AHmYpgQ" target="_0GeWUgl0Ee6loP0AHmYpgQ" source="_0GWagAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0PJKIQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0PJKIgl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0PKYQAl0Ee6loP0AHmYpgQ" target="_0GhZoAl0Ee6loP0AHmYpgQ" source="_0GY2wAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0PKYQQl0Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0PKYQgl0Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CsPJAAl5Ee6loP0AHmYpgQ" target="_0GHJ8Al0Ee6loP0AHmYpgQ" source="_iKCzsAl5Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CsPJAQl5Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_CsPJAgl5Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_N10FgAl5Ee6loP0AHmYpgQ" target="_0FyZ0Al0Ee6loP0AHmYpgQ" source="_gzi60Al5Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_N10FgQl5Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_N10Fggl5Ee6loP0AHmYpgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cTfakAl6Ee6loP0AHmYpgQ" target="_0FQOUAl0Ee6loP0AHmYpgQ" source="_rTq1MAl6Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cTfakQl6Ee6loP0AHmYpgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_cTfakgl6Ee6loP0AHmYpgQ" name="newScript()" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3FImwAnrEe6-OJ1qbTi2_g" target="_0FNyEAl0Ee6loP0AHmYpgQ" source="_0FSqkAl0Ee6loP0AHmYpgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3FImwQnrEe6-OJ1qbTi2_g"/>
        <condition xmi:type="expression:Expression" xmi:id="_3FImwgnrEe6-OJ1qbTi2_g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_WQtDoAl4Ee6loP0AHmYpgQ" name="Gestor de Projeto" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_0E0wlAl0Ee6loP0AHmYpgQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0E0wgQl0Ee6loP0AHmYpgQ">
        <name xmi:type="expression:Expression" xmi:id="_0E0wggl0Ee6loP0AHmYpgQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0E0wgwl0Ee6loP0AHmYpgQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0E0whAl0Ee6loP0AHmYpgQ">
        <name xmi:type="expression:Expression" xmi:id="_0E0whQl0Ee6loP0AHmYpgQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0E0whgl0Ee6loP0AHmYpgQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0E0whwl0Ee6loP0AHmYpgQ">
        <name xmi:type="expression:Expression" xmi:id="_0E0wiAl0Ee6loP0AHmYpgQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0E0wiQl0Ee6loP0AHmYpgQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0E0wigl0Ee6loP0AHmYpgQ">
        <name xmi:type="expression:Expression" xmi:id="_0E0wiwl0Ee6loP0AHmYpgQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0E0wjAl0Ee6loP0AHmYpgQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0E0wjQl0Ee6loP0AHmYpgQ">
        <name xmi:type="expression:Expression" xmi:id="_0E0wjgl0Ee6loP0AHmYpgQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0E0wjwl0Ee6loP0AHmYpgQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_0EQIwgl0Ee6loP0AHmYpgQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_0EQIwwl0Ee6loP0AHmYpgQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_0EQIxAl0Ee6loP0AHmYpgQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_0EQIxQl0Ee6loP0AHmYpgQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_0EQIxgl0Ee6loP0AHmYpgQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_0EQIxwl0Ee6loP0AHmYpgQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_0EQIyAl0Ee6loP0AHmYpgQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_0EQIyQl0Ee6loP0AHmYpgQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_0EQIygl0Ee6loP0AHmYpgQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_0EQIwAl0Ee6loP0AHmYpgQ" type="Process" element="_0EPhsAl0Ee6loP0AHmYpgQ" name="Definitions_1" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_0E1XkAl0Ee6loP0AHmYpgQ" type="2007" element="_0E0wgAl0Ee6loP0AHmYpgQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_0E1XlQl0Ee6loP0AHmYpgQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_0E1Xlgl0Ee6loP0AHmYpgQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_0E6QEAl0Ee6loP0AHmYpgQ" type="3007" element="_0E5pAAl0Ee6loP0AHmYpgQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_0E6QFQl0Ee6loP0AHmYpgQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_0E6QFgl0Ee6loP0AHmYpgQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_0FCL4Al0Ee6loP0AHmYpgQ" type="3002" element="_0FBk0Al0Ee6loP0AHmYpgQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0FCL4gl0Ee6loP0AHmYpgQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0FCL4wl0Ee6loP0AHmYpgQ" x="-21" y="13"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0FCL4Ql0Ee6loP0AHmYpgQ" x="82" y="307"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0FEoKwl0Ee6loP0AHmYpgQ" type="3063" element="_0FEoIAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0FFPMAl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0FEoLAl0Ee6loP0AHmYpgQ" x="170" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0FISiQl0Ee6loP0AHmYpgQ" type="3027" element="_0FISgAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0FISiwl0Ee6loP0AHmYpgQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0FISigl0Ee6loP0AHmYpgQ" x="850" y="465"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0FLV2Ql0Ee6loP0AHmYpgQ" type="3027" element="_0FLV0Al0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0FLV2wl0Ee6loP0AHmYpgQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0FLV2gl0Ee6loP0AHmYpgQ" x="1020" y="465"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0FOZIAl0Ee6loP0AHmYpgQ" type="3008" element="_0FNyEAl0Ee6loP0AHmYpgQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0FOZIgl0Ee6loP0AHmYpgQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0FOZIwl0Ee6loP0AHmYpgQ" x="1" y="19"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0FOZIQl0Ee6loP0AHmYpgQ" x="3112" y="289"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0FQOVAl0Ee6loP0AHmYpgQ" type="3008" element="_0FQOUAl0Ee6loP0AHmYpgQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0FQOVgl0Ee6loP0AHmYpgQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0FQ1YAl0Ee6loP0AHmYpgQ" x="114" y="-64"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0FQOVQl0Ee6loP0AHmYpgQ" x="2949" y="142"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0FSqmwl0Ee6loP0AHmYpgQ" type="3063" element="_0FSqkAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0FSqnQl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0FSqnAl0Ee6loP0AHmYpgQ" x="2835" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0FVG2wl0Ee6loP0AHmYpgQ" type="3063" element="_0FVG0Al0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0FVt4Al0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0FVG3Al0Ee6loP0AHmYpgQ" x="3580" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0FYKIAl0Ee6loP0AHmYpgQ" type="3063" element="_0FXjEAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0FYKIgl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0FYKIQl0Ee6loP0AHmYpgQ" x="3930" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0FZ_VAl0Ee6loP0AHmYpgQ" type="3003" element="_0FZ_UAl0Ee6loP0AHmYpgQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0FZ_Vgl0Ee6loP0AHmYpgQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0FZ_Vwl0Ee6loP0AHmYpgQ" y="13"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0FZ_VQl0Ee6loP0AHmYpgQ" x="4672" y="307"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0FcbmQl0Ee6loP0AHmYpgQ" type="3027" element="_0FcbkAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0Fcbmwl0Ee6loP0AHmYpgQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0Fcbmgl0Ee6loP0AHmYpgQ" x="4470" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0Fe31Al0Ee6loP0AHmYpgQ" type="3008" element="_0Fe30Al0Ee6loP0AHmYpgQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0Fe31gl0Ee6loP0AHmYpgQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0Fe31wl0Ee6loP0AHmYpgQ" x="52" y="-64"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0Fe31Ql0Ee6loP0AHmYpgQ" x="2217" y="300"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0Fv9kAl0Ee6loP0AHmYpgQ" type="3063" element="_0FvWgAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0Fv9kgl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0Fv9kQl0Ee6loP0AHmYpgQ" x="1820" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0FyZ1Al0Ee6loP0AHmYpgQ" type="3008" element="_0FyZ0Al0Ee6loP0AHmYpgQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0FzA4Al0Ee6loP0AHmYpgQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0FzA4Ql0Ee6loP0AHmYpgQ" x="36" y="-90"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0FyZ1Ql0Ee6loP0AHmYpgQ" x="1265" y="288"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0F02Gwl0Ee6loP0AHmYpgQ" type="3063" element="_0F02EAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0F1dIAl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0F02HAl0Ee6loP0AHmYpgQ" x="1380" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0F3SVAl0Ee6loP0AHmYpgQ" type="3008" element="_0F3SUAl0Ee6loP0AHmYpgQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0F3SVgl0Ee6loP0AHmYpgQ" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0F3SVwl0Ee6loP0AHmYpgQ" x="-39" y="-205"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0F3SVQl0Ee6loP0AHmYpgQ" x="1705" y="288"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0F6VoAl0Ee6loP0AHmYpgQ" type="3008" element="_0F5ukAl0Ee6loP0AHmYpgQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0F6Vogl0Ee6loP0AHmYpgQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0F6Vowl0Ee6loP0AHmYpgQ" x="-8" y="-80"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0F6VoQl0Ee6loP0AHmYpgQ" x="635" y="288"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0F9Y8Al0Ee6loP0AHmYpgQ" type="3063" element="_0F8x4Al0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0F9Y8gl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0F9Y8Ql0Ee6loP0AHmYpgQ" x="890" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0F_1MAl0Ee6loP0AHmYpgQ" type="3063" element="_0F_OIAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0F_1Mgl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0F_1MQl0Ee6loP0AHmYpgQ" x="470" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0GCReAl0Ee6loP0AHmYpgQ" type="3027" element="_0GBqYAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0GCRegl0Ee6loP0AHmYpgQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0GCReQl0Ee6loP0AHmYpgQ" x="2480" y="85"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0GEtsAl0Ee6loP0AHmYpgQ" type="3008" element="_0GEGoAl0Ee6loP0AHmYpgQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0GEtsgl0Ee6loP0AHmYpgQ" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0GEtswl0Ee6loP0AHmYpgQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0GEtsQl0Ee6loP0AHmYpgQ" x="2625" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0GHJ9Al0Ee6loP0AHmYpgQ" type="3008" element="_0GHJ8Al0Ee6loP0AHmYpgQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0GHxAAl0Ee6loP0AHmYpgQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0GHxAQl0Ee6loP0AHmYpgQ" x="-9" y="-54"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0GHJ9Ql0Ee6loP0AHmYpgQ" x="2375" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0GJmOwl0Ee6loP0AHmYpgQ" type="3063" element="_0GJmMAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0GJmPQl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0GJmPAl0Ee6loP0AHmYpgQ" x="2000" y="285" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0GMphAl0Ee6loP0AHmYpgQ" type="3063" element="_0GMCcAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0GMphgl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0GMphQl0Ee6loP0AHmYpgQ" x="1530" y="285" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0GPFwAl0Ee6loP0AHmYpgQ" type="3063" element="_0GOesAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0GPFwgl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0GPFwQl0Ee6loP0AHmYpgQ" x="1007" y="284" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0GQ6-wl0Ee6loP0AHmYpgQ" type="3063" element="_0GQ68Al0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0GQ6_Ql0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0GQ6_Al0Ee6loP0AHmYpgQ" x="730" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0GT-Swl0Ee6loP0AHmYpgQ" type="3063" element="_0GT-QAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0GUlUAl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0GT-TAl0Ee6loP0AHmYpgQ" x="310" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0GXBkAl0Ee6loP0AHmYpgQ" type="3063" element="_0GWagAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0GXBkgl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0GXBkQl0Ee6loP0AHmYpgQ" x="3220" y="285" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0GZd0Al0Ee6loP0AHmYpgQ" type="3063" element="_0GY2wAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0GZd0gl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0GZd0Ql0Ee6loP0AHmYpgQ" x="4090" y="285" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0Gb6EAl0Ee6loP0AHmYpgQ" type="3063" element="_0GbTAAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0Gb6Egl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0Gb6EQl0Ee6loP0AHmYpgQ" x="3760" y="285" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0Ge9Zwl0Ee6loP0AHmYpgQ" type="3063" element="_0GeWUgl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0Ge9aQl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0Ge9aAl0Ee6loP0AHmYpgQ" x="3410" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0GhZqwl0Ee6loP0AHmYpgQ" type="3063" element="_0GhZoAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0GiAsQl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0GiAsAl0Ee6loP0AHmYpgQ" x="4270" y="285"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0Gkc-wl0Ee6loP0AHmYpgQ" type="3063" element="_0Gkc8Al0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0Gkc_Ql0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0Gkc_Al0Ee6loP0AHmYpgQ" x="2680" y="285" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0GngSwl0Ee6loP0AHmYpgQ" type="3063" element="_0GngQAl0Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0GngTQl0Ee6loP0AHmYpgQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0GngTAl0Ee6loP0AHmYpgQ" x="2480" y="205" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_0PNbkAl0Ee6loP0AHmYpgQ" type="3015" element="_0PM0gAl0Ee6loP0AHmYpgQ">
              <children xmi:type="notation:DecorationNode" xmi:id="_0PNblQl0Ee6loP0AHmYpgQ" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_0PNbkQl0Ee6loP0AHmYpgQ"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_0PNbkgl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_0PNbkwl0Ee6loP0AHmYpgQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0PNblAl0Ee6loP0AHmYpgQ" x="4336" y="135" width="174" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gzjh4gl5Ee6loP0AHmYpgQ" type="3005" element="_gzi60Al5Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_gzjh5Al5Ee6loP0AHmYpgQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gzjh4wl5Ee6loP0AHmYpgQ" x="1149" y="284" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_iKDazAl5Ee6loP0AHmYpgQ" type="3005" element="_iKCzsAl5Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_iKDazgl5Ee6loP0AHmYpgQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iKDazQl5Ee6loP0AHmYpgQ" x="2259" y="97" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rTrcTAl6Ee6loP0AHmYpgQ" type="3005" element="_rTq1MAl6Ee6loP0AHmYpgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_rTsDUAl6Ee6loP0AHmYpgQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rTrcTQl6Ee6loP0AHmYpgQ" x="3063" y="139" width="100" height="49"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_0E6QEQl0Ee6loP0AHmYpgQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_0E6QEgl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_0E6QEwl0Ee6loP0AHmYpgQ" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_0E6QFwl0Ee6loP0AHmYpgQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0E6QFAl0Ee6loP0AHmYpgQ" x="640" height="600"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_0E1XkQl0Ee6loP0AHmYpgQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_0E1Xkgl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_0E1Xkwl0Ee6loP0AHmYpgQ" lineColor="12632256"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_0E1Xlwl0Ee6loP0AHmYpgQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0E1XlAl0Ee6loP0AHmYpgQ" width="4815" height="665"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_0EQIwQl0Ee6loP0AHmYpgQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_0NwqEwl0Ee6loP0AHmYpgQ" type="4001" element="_0NwqEAl0Ee6loP0AHmYpgQ" source="_0FCL4Al0Ee6loP0AHmYpgQ" target="_0FEoKwl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0NwqFgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0NwqFwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0NwqFAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0NwqFQl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0NztYAl0Ee6loP0AHmYpgQ" type="4001" element="_0NzGUAl0Ee6loP0AHmYpgQ" source="_0FEoKwl0Ee6loP0AHmYpgQ" target="_0GT-Swl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0NztYwl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0NztZAl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0NztYQl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0NztYgl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0N2Jowl0Ee6loP0AHmYpgQ" type="4001" element="_0N2JoAl0Ee6loP0AHmYpgQ" source="_0F6VoAl0Ee6loP0AHmYpgQ" target="_0FISiQl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0N2Jpgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0N2Jpwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0N2JpAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0N2JpQl0Ee6loP0AHmYpgQ" points="[-1, 20, -245, -149]$[-1, 167, -245, -2]$[194, 167, -50, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0N4l4Al0Ee6loP0AHmYpgQ" type="4001" element="_0N3-0Al0Ee6loP0AHmYpgQ" source="_0FISiQl0Ee6loP0AHmYpgQ" target="_0FLV2Ql0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0N4l4wl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0N4l5Al0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0N4l4Ql0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0N4l4gl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0N6bEwl0Ee6loP0AHmYpgQ" type="4001" element="_0N6bEAl0Ee6loP0AHmYpgQ" source="_0FLV2Ql0Ee6loP0AHmYpgQ" target="_0FyZ1Al0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0N6bFgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0N6bFwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0N6bFAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0N6bFQl0Ee6loP0AHmYpgQ" points="[50, -2, -166, 167]$[215, -2, -1, 167]$[215, -149, -1, 20]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0N_TkAl0Ee6loP0AHmYpgQ" type="4001" element="_0N-sgAl0Ee6loP0AHmYpgQ" source="_0FOZIAl0Ee6loP0AHmYpgQ" target="_rTrcTAl6Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0N_Tkwl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0N_TlAl0Ee6loP0AHmYpgQ" x="-8" y="37"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0N_TkQl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0N_Tkgl0Ee6loP0AHmYpgQ" points="[0, -21, 20, 125]$[0, -121, 20, 25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OBIwwl0Ee6loP0AHmYpgQ" type="4001" element="_0OBIwAl0Ee6loP0AHmYpgQ" source="_0FOZIAl0Ee6loP0AHmYpgQ" target="_0GXBkAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OBIxgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OBIxwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OBIxAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OBIxQl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OC98wl0Ee6loP0AHmYpgQ" type="4001" element="_0OC98Al0Ee6loP0AHmYpgQ" source="_0FQOVAl0Ee6loP0AHmYpgQ" target="_0F9Y8Al0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OC99gl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OC99wl0Ee6loP0AHmYpgQ" x="-1060" y="-28"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OC99Al0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OC99Ql0Ee6loP0AHmYpgQ" points="[-3, -18, 2027, -165]$[-3, -137, 2027, -284]$[-2039, -137, -9, -284]$[-2039, 122, -9, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OFaMAl0Ee6loP0AHmYpgQ" type="4001" element="_0OEzIAl0Ee6loP0AHmYpgQ" source="_0FQOVAl0Ee6loP0AHmYpgQ" target="_0FSqmwl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OFaMwl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OFaNAl0Ee6loP0AHmYpgQ" x="23" y="43"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OFaMQl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OFaMgl0Ee6loP0AHmYpgQ" points="[-1, 20, 84, -127]$[-1, 91, 84, -56]$[-59, 91, 26, -56]$[-59, 122, 26, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OHPYAl0Ee6loP0AHmYpgQ" type="4001" element="_0OGoUAl0Ee6loP0AHmYpgQ" source="_0Gkc-wl0Ee6loP0AHmYpgQ" target="_0FSqmwl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OHPYwl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OHPZAl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OHPYQl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OHPYgl0Ee6loP0AHmYpgQ" points="[50, -2, -220, -2]$[220, -2, -50, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OJEkAl0Ee6loP0AHmYpgQ" type="4001" element="_0OIdgAl0Ee6loP0AHmYpgQ" source="_0Fe31Al0Ee6loP0AHmYpgQ" target="_0FSqmwl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OJEkwl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OJElAl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OJEkQl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OJEkgl0Ee6loP0AHmYpgQ" points="[5, 17, -642, 28]$[5, 86, -642, 97]$[646, 86, -1, 97]$[646, 14, -1, 25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OKSswl0Ee6loP0AHmYpgQ" type="4001" element="_0OKSsAl0Ee6loP0AHmYpgQ" source="_0GEtsAl0Ee6loP0AHmYpgQ" target="_0FSqmwl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OKStgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OKStwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OKStAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OKStQl0Ee6loP0AHmYpgQ" points="[8, -13, -231, -202]$[226, -13, -13, -202]$[226, 164, -13, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OMH4wl0Ee6loP0AHmYpgQ" type="4001" element="_0OMH4Al0Ee6loP0AHmYpgQ" source="_0Ge9Zwl0Ee6loP0AHmYpgQ" target="_0FVG2wl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OMH5gl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OMH5wl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OMH5Al0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OMH5Ql0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0ON9Ewl0Ee6loP0AHmYpgQ" type="4001" element="_0ON9EAl0Ee6loP0AHmYpgQ" source="_0FVG2wl0Ee6loP0AHmYpgQ" target="_0Gb6EAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0ON9Fgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0ON9Fwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0ON9FAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0ON9FQl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OPyQAl0Ee6loP0AHmYpgQ" type="4001" element="_0OPLMAl0Ee6loP0AHmYpgQ" source="_0Gb6EAl0Ee6loP0AHmYpgQ" target="_0FYKIAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OPyQwl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OPyRAl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OPyQQl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OPyQgl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OaxYwl0Ee6loP0AHmYpgQ" type="4001" element="_0OaxYAl0Ee6loP0AHmYpgQ" source="_0FYKIAl0Ee6loP0AHmYpgQ" target="_0GZd0Al0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OaxZgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OebwAl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OaxZAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OaxZQl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OgQ8wl0Ee6loP0AHmYpgQ" type="4001" element="_0OgQ8Al0Ee6loP0AHmYpgQ" source="_0FcbmQl0Ee6loP0AHmYpgQ" target="_0FZ_VAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OgQ9gl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OgQ9wl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OgQ9Al0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OgQ9Ql0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OiGIwl0Ee6loP0AHmYpgQ" type="4001" element="_0OiGIAl0Ee6loP0AHmYpgQ" source="_0GhZqwl0Ee6loP0AHmYpgQ" target="_0FcbmQl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OiGJgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OiGJwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OiGJAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OiGJQl0Ee6loP0AHmYpgQ" points="[50, -2, -150, -2]$[150, -2, -50, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0Oj7Uwl0Ee6loP0AHmYpgQ" type="4001" element="_0Oj7UAl0Ee6loP0AHmYpgQ" source="_0GJmOwl0Ee6loP0AHmYpgQ" target="_0Fe31Al0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0Oj7Vgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0Oj7Vwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0Oj7VAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0Oj7VQl0Ee6loP0AHmYpgQ" points="[50, 10, -156, -1]$[186, 10, -20, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OmXkwl0Ee6loP0AHmYpgQ" type="4001" element="_0OmXkAl0Ee6loP0AHmYpgQ" source="_0Fe31Al0Ee6loP0AHmYpgQ" target="_0Gkc-wl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OmXlgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OmXlwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OmXlAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OmXlQl0Ee6loP0AHmYpgQ" points="[20, -1, -467, 4]$[424, -1, -63, 4]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0Ooz0gl0Ee6loP0AHmYpgQ" type="4001" element="_0OoMwAl0Ee6loP0AHmYpgQ" source="_0Fe31Al0Ee6loP0AHmYpgQ" target="_iKDazAl5Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0Ooz1Ql0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0Ooz1gl0Ee6loP0AHmYpgQ" y="-31"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0Ooz0wl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0Ooz1Al0Ee6loP0AHmYpgQ" points="[-1, -20, -73, 178]$[-1, -200, -73, -2]$[22, -200, -50, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OqpAwl0Ee6loP0AHmYpgQ" type="4001" element="_0OqpAAl0Ee6loP0AHmYpgQ" source="_0F3SVAl0Ee6loP0AHmYpgQ" target="_0Fv9kAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OrQEAl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OrQEQl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OqpBAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OqpBQl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OseMwl0Ee6loP0AHmYpgQ" type="4001" element="_0OseMAl0Ee6loP0AHmYpgQ" source="_0Fv9kAl0Ee6loP0AHmYpgQ" target="_0GJmOwl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OseNgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OseNwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OseNAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OseNQl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OuTYwl0Ee6loP0AHmYpgQ" type="4001" element="_0OuTYAl0Ee6loP0AHmYpgQ" source="_0GPFwAl0Ee6loP0AHmYpgQ" target="_gzjh4gl5Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OuTZgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OuTZwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OuTZAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OuTZQl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0OwIkgl0Ee6loP0AHmYpgQ" type="4001" element="_0OvhgAl0Ee6loP0AHmYpgQ" source="_0FyZ1Al0Ee6loP0AHmYpgQ" target="_0F3SVAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0OwIlQl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0OwIlgl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0OwIkwl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0OwIlAl0Ee6loP0AHmYpgQ" points="[21, 1, -419, -11]$[21, 117, -419, 105]$[440, 117, 0, 105]$[440, 34, 0, 22]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0Oyk0gl0Ee6loP0AHmYpgQ" type="4001" element="_0Ox9wAl0Ee6loP0AHmYpgQ" source="_0FyZ1Al0Ee6loP0AHmYpgQ" target="_0F02Gwl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0Oyk1Ql0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0Oyk1gl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0Oyk0wl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0Oyk1Al0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0O0aAwl0Ee6loP0AHmYpgQ" type="4001" element="_0O0aAAl0Ee6loP0AHmYpgQ" source="_0F02Gwl0Ee6loP0AHmYpgQ" target="_0GMphAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0O0aBgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0O0aBwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0O0aBAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0O0aBQl0Ee6loP0AHmYpgQ" points="[50, -2, -100, -2]$[100, -2, -50, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0O2PMAl0Ee6loP0AHmYpgQ" type="4001" element="_0O1oIAl0Ee6loP0AHmYpgQ" source="_0GMphAl0Ee6loP0AHmYpgQ" target="_0F3SVAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0O2PMwl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0O2PNAl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0O2PMQl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0O2PMgl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0O3dUwl0Ee6loP0AHmYpgQ" type="4001" element="_0O3dUAl0Ee6loP0AHmYpgQ" source="_0F_1MAl0Ee6loP0AHmYpgQ" target="_0F6VoAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0O4EYAl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0O4EYQl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0O3dVAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0O3dVQl0Ee6loP0AHmYpgQ" points="[50, -2, -86, -1]$[116, -2, -20, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0O5Sgwl0Ee6loP0AHmYpgQ" type="4001" element="_0O5SgAl0Ee6loP0AHmYpgQ" source="_0F6VoAl0Ee6loP0AHmYpgQ" target="_0GQ6-wl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0O5Shgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0O5Shwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0O5ShAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0O5ShQl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0O7uwwl0Ee6loP0AHmYpgQ" type="4001" element="_0O7uwAl0Ee6loP0AHmYpgQ" source="_0GQ6-wl0Ee6loP0AHmYpgQ" target="_0F9Y8Al0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0O7uxgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0O7uxwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0O7uxAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0O7uxQl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0O9j8wl0Ee6loP0AHmYpgQ" type="4001" element="_0O9j8Al0Ee6loP0AHmYpgQ" source="_0F9Y8Al0Ee6loP0AHmYpgQ" target="_0GPFwAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0O9j9gl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0O9j9wl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0O9j9Al0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0O9j9Ql0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0O_ZIAl0Ee6loP0AHmYpgQ" type="4001" element="_0O-yEAl0Ee6loP0AHmYpgQ" source="_0GT-Swl0Ee6loP0AHmYpgQ" target="_0F_1MAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0O_ZIwl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0O_ZJAl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0O_ZIQl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0O_ZIgl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0PBOUAl0Ee6loP0AHmYpgQ" type="4001" element="_0PAnQAl0Ee6loP0AHmYpgQ" source="_0GHJ9Al0Ee6loP0AHmYpgQ" target="_0GCReAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0PBOUwl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0PBOVAl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0PBOUQl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0PBOUgl0Ee6loP0AHmYpgQ" points="[20, -1, -114, 10]$[84, -1, -50, 10]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0PDDgwl0Ee6loP0AHmYpgQ" type="4001" element="_0PDDgAl0Ee6loP0AHmYpgQ" source="_0GCReAl0Ee6loP0AHmYpgQ" target="_0GEtsAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0PDqkAl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0PDqkQl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0PDDhAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0PDDhQl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0PFfwwl0Ee6loP0AHmYpgQ" type="4001" element="_0PFfwAl0Ee6loP0AHmYpgQ" source="_0GngSwl0Ee6loP0AHmYpgQ" target="_0GEtsAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0PFfxgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0PFfxwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0PFfxAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0PFfxQl0Ee6loP0AHmYpgQ" points="[50, -2, -66, 107]$[115, -2, -1, 107]$[115, -89, -1, 20]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0PHU8Al0Ee6loP0AHmYpgQ" type="4001" element="_0PGt4Al0Ee6loP0AHmYpgQ" source="_0GHJ9Al0Ee6loP0AHmYpgQ" target="_0GngSwl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0PHU8wl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0PHU9Al0Ee6loP0AHmYpgQ" x="-29" y="-32"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0PHU8Ql0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0PHU8gl0Ee6loP0AHmYpgQ" points="[-1, 20, -148, -95]$[-1, 110, -148, -5]$[84, 110, -63, -5]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0PJKIwl0Ee6loP0AHmYpgQ" type="4001" element="_0PJKIAl0Ee6loP0AHmYpgQ" source="_0GXBkAl0Ee6loP0AHmYpgQ" target="_0Ge9Zwl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0PJKJgl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0PJKJwl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0PJKJAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0PJKJQl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0PKYQwl0Ee6loP0AHmYpgQ" type="4001" element="_0PKYQAl0Ee6loP0AHmYpgQ" source="_0GZd0Al0Ee6loP0AHmYpgQ" target="_0GhZqwl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_0PK_UAl0Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0PK_UQl0Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0PKYRAl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0PKYRQl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0PP30Ql0Ee6loP0AHmYpgQ" type="4003" element="_0PP30Al0Ee6loP0AHmYpgQ" source="_0PNbkAl0Ee6loP0AHmYpgQ" target="_0GhZqwl0Ee6loP0AHmYpgQ">
      <styles xmi:type="notation:FontStyle" xmi:id="_0PP30gl0Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0PP30wl0Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CsPJAwl5Ee6loP0AHmYpgQ" type="4001" element="_CsPJAAl5Ee6loP0AHmYpgQ" source="_iKDazAl5Ee6loP0AHmYpgQ" target="_0GHJ9Al0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CsPJBgl5Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CsPJBwl5Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CsPJBAl5Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CsPJBQl5Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_N10Fgwl5Ee6loP0AHmYpgQ" type="4001" element="_N10FgAl5Ee6loP0AHmYpgQ" source="_gzjh4gl5Ee6loP0AHmYpgQ" target="_0FyZ1Al0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_N10skAl5Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_N10skQl5Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_N10FhAl5Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_N10FhQl5Ee6loP0AHmYpgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cTfakwl6Ee6loP0AHmYpgQ" type="4001" element="_cTfakAl6Ee6loP0AHmYpgQ" source="_rTrcTAl6Ee6loP0AHmYpgQ" target="_0FQOVAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cTgBoAl6Ee6loP0AHmYpgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cTgBoQl6Ee6loP0AHmYpgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cTfalAl6Ee6loP0AHmYpgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cTfalQl6Ee6loP0AHmYpgQ" points="[-50, -2, 74, -1]$[-104, -2, 20, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3FJN0AnrEe6-OJ1qbTi2_g" type="4001" element="_3FImwAnrEe6-OJ1qbTi2_g" source="_0FSqmwl0Ee6loP0AHmYpgQ" target="_0FOZIAl0Ee6loP0AHmYpgQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3FJN0wnrEe6-OJ1qbTi2_g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3FJN1AnrEe6-OJ1qbTi2_g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3FJN0QnrEe6-OJ1qbTi2_g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3FJN0gnrEe6-OJ1qbTi2_g" points="[0, -6, -198, 2]$[204, 8, 6, 16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3FJ04AnrEe6-OJ1qbTi2_g" id="(1.0,0.66)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
