== Migration notes (June 10, 2023 at 4:03:15 PM WEST)

=== Updates

* `bonita.runtime.version` has been updated from `7.15.0` to `8.0.0`.
* `bonita-project-maven-plugin.version` has been updated from `0.0.6` to `0.1.0`.
* `com.company.model:bdm-client:jar:1.0.0` dependency has been replaced with `${project.groupId}:sie-projeto-bonita-bdm-model:jar:${project.version}`.
* The project layout has been changed in favor of a multi modules maven project. It means that files location inside the project have changed.  It is a technical change and will not impact the design usage in Bonita Studio.New maven modules and their respective `pom.xml` files are *reserved for internal Studio use*.
* Project's Business Data Model is now build in its own maven module. While it does not impact the design usage, it can now be built and deployed independently from a Studio.  The BDM model dependency share the same `version` and `groupId` of the parent project. It is enforced by the format of the Bonita project and must not be changed.

